name: tfc
description: "Time For Change(TFC) display framework."
version: 2025.2.0
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  beamer: ^1.6.2
  flutter_svg: ^2.0.10
  logger: ^2.4.0
  nm: ^0.5.0
  dbus: ^0.7.11
  dartssh2: ^2.11.0
  shared_preferences: ^2.3.5
  file_picker: ^10.3.3
  rxdart: ^0.28.0
  font_awesome_flutter: ^10.9.1
  riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_colorpicker: ^1.1.0
  open62541:
    # path: ../open62541_dart
    git:
      url: https://github.com/centroid-is/open62541_dart.git
      ref: isolate-client-browse
  postgres: ^3.4.5
  intl: ^0.20.2
  collection: ^1.18.0
  community_charts_flutter: ^1.0.4
  meta: ^1.15.0
  drift: ^2.28.0
  drift_postgres: ^1.3.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  path: ^1.9.0
  basic_utils: ^5.7.0
  amplify_secure_storage_dart: ^0.5.6
  cryptography_flutter: ^2.3.2
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.4
  board_datetime_picker:
    git:
      url: https://github.com/centroid-is/board_datetime_picker.git
      ref: subtitle-for-start-end-date
  cristalyse:
    # path: ../cristalyse
    git:
      url: https://github.com/centroid-is/cristalyse.git
      ref: dev
  tfc_dart:
    path: packages/tfc_dart
dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/centroid.svg
  fonts:
    - family: TfcIcons
      fonts:
        - asset: assets/fonts/TfcIcons.ttf
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package




# dependency_overrides:
#   open62541:
#     path: ../open62541_bindings
#   postgres:
#     path: ../postgresql-dart
#   stream_channel: ^2.1.4
#   stack_trace: ^1.12.1
#   meta: ^1.16.0
#   collection: ^1.19.0
#   async: ^2.12.0