name: tfc_dart
description: Core functionality and converters for TFC (Time For Change) display framework
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  # JSON serialization
  json_annotation: ^4.9.0

  # State management and reactive programming
  rxdart: ^0.28.0

  # Logging
  logger: ^2.4.0

  # Database
  drift: ^2.28.0
  drift_postgres: ^1.3.1
  postgres:
    git:
      url: https://github.com/centroid-is/postgresql-dart.git
      ref: add-keepalive

  # Secure storage
  amplify_secure_storage_dart: ^0.5.6

  # OPC UA
  open62541:
    git:
      url: https://github.com/centroid-is/open62541_dart.git
      ref: isolate-client-browse

  # Utilities
  collection: ^1.18.0
  path: ^1.9.1
  args: ^2.4.2
  basic_utils: ^5.7.0

dependency_overrides:
  postgres:
    git:
      url: https://github.com/centroid-is/postgresql-dart.git
      ref: add-keepalive

dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  drift_dev: ^2.28.0
  test: ^1.25.0
