name: Build and Push centroid-hmi Docker Image

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  elinux-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/centroid-is/tfc-toolchain:latest
    outputs:
      centroid_hmi_sha: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Make safe directory
        run: git config --system --add safe.directory '*'
      - name: Checkout centroid-hmi
        uses: actions/checkout@v4

      - name: Get commit SHA
        id: get_sha
        working-directory: centroid-hmi
        run: |
          SHA=$(git rev-parse --short HEAD) || exit 1
          test -n "$SHA" || (echo "Empty SHA"; exit 1)
          echo "SHA: $SHA"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"

      - name: Setup elinux platform
        working-directory: centroid-hmi
        run: flutter-elinux create --platforms=elinux .

      - name: Get Flutter Packages
        working-directory: centroid-hmi
        run: flutter-elinux pub get

      - name: Build for eLinux
        working-directory: centroid-hmi
        run: flutter-elinux build elinux --debug

      - name: Move build artifacts
        working-directory: centroid-hmi
        run: |
          mkdir -p assets
          mv build/elinux/x64/debug/bundle/* assets/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: centroid-hmi-artifacts
          path: centroid-hmi/assets/

  docker-build:
    needs: elinux-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: centroid-hmi-artifacts
          path: docker/frontend/bundle

      - name: List files in frontend/bundle
        run: ls -l docker/frontend/bundle

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: docker/frontend
          push: true
          build-args: |
            APP_BIN=centroidx
            APP_BUNDLE=bundle
          tags: |
            ghcr.io/${{ github.repository_owner }}/centroid-hmi:${{ needs.elinux-build.outputs.centroid_hmi_sha }}
            ghcr.io/${{ github.repository_owner }}/centroid-hmi:latest

      - name: Build and push Docker image (PR)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: docker/frontend
          push: true
          build-args: |
            APP_BIN=centroidx
            APP_BUNDLE=bundle
          tags: |
            ghcr.io/${{ github.repository_owner }}/centroid-hmi:pr-${{ github.event.pull_request.number }}

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit SHA
        id: get_sha
        run: |
          SHA=$(git rev-parse --short HEAD) || exit 1
          test -n "$SHA" || (echo "Empty SHA"; exit 1)
          echo "SHA: $SHA"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image (main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: packages/tfc_dart
          file: docker/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/centroid-backend:${{ steps.get_sha.outputs.sha }}
            ghcr.io/${{ github.repository_owner }}/centroid-backend:latest

      - name: Build and push backend Docker image (PR)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: packages/tfc_dart
          file: docker/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/centroid-backend:pr-${{ github.event.pull_request.number }}